name: Create PR for hotfix
on:
  pull_request:
    branches:
      - main
    types: [opened]
jobs:
  hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: onpointvn/create-pull-request-action@v1
        name: Create PR to develop
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: hotfix
          base_branch: develop
          labels: develop,automerge
          assignees: phuongtruongonpoint
          reviewers: phuongtruongonpoint
      - uses: onpointvn/create-pull-request-action@v1
        name: Create PR to integration
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: hotfix
          base_branch: integration
          labels: integration,automerge
          assignees: phuongtruongonpoint
          reviewers: phuongtruongonpoint

  automerge:
    needs: hotfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: feedback
        run: echo "1 ${{steps}}"